image: gitpod/workspace-base

tasks:
- name: install all softwares and download databases
  init: |
    curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
    bash Mambaforge-$(uname)-$(uname -m).sh -b -p /workspace/conda && rm Mambaforge-$(uname)-$(uname -m).sh
    /workspace/conda/bin/mamba init bash
    source ${HOME}/.bashrc
    mamba create -n omacademy -c conda-forge python=3.9 -y
    mamba activate omacademy
    cd Module_FastOMA/working_dir/
    wget https://github.com/DessimozLab/FastOMA/archive/refs/heads/main.zip
    unzip main.zip
    mv FastOMA-main FastOMA
    cd FastOMA
    pip3 install --upgrade pip
    pip3 install .[report,nextflow]
    cd ../../../
    mamba install -c bioconda mafft -y 
    mamba install -c bioconda fasttree -y
    mamba install -c bioconda iqtree -y
    mamba install -c conda-forge openjdk -y
    pip install pyham
    echo 'mamba activate omacademy' >> ${HOME}/.bashrc
    cd /workspace/FastOMA-academy/Module_FastOMA/
    curl -L -O "https://omabrowser.org/All/Saccharomyceta.h5"
    cp Saccharomyceta.h5 working_dir/in_folder/omamerdb.h5
    cd working_dir


  command: |
    source ${HOME}/.bashrc

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"